version: "3.9"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./template.xlsx:/code/template.xlsx
      - ./generated:/code/generated # Excel/PDF 出力先
